[build]
  command = "npm run build"
  publish = ".next"

# Configurações de plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Cabeçalhos de segurança e otimização
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.google-analytics.com *.googletagmanager.com *.facebook.net *.clarity.ms; style-src 'self' 'unsafe-inline'; img-src 'self' data: *.google-analytics.com *.facebook.com; font-src 'self' data:; connect-src 'self' *.google-analytics.com *.facebook.com; frame-src 'self' *.facebook.com;"

# Cache para recursos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirecionamentos
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# Redirecionamento de erros para página 404 personalizada
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Forçar HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
